#:schema node_modules/wrangler/config-schema.json
name = "sublinkworker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "b1e975fb492d41f480f0076624f484ac" }
]

[assets]
directory = "./public"
